name: Generate gallery and deploy site

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allows manual runs

permissions:
  contents: write      # Needed for committing changes
  pages: write         # Required for deploying GitHub Pages
  id-token: write      # Required for authentication

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create directory
        run: mkdir -p ${{ github.workspace }}/fotogalerie && ls -la ${{ github.workspace }}

      - name: Ensure directory is writable
        run: chmod -R 777 ${{ github.workspace }}/fotogalerie

      - name: Clear old files safely
        run: |
            if [ -d "${{ github.workspace }}/fotogalerie" ]; then
                rm -rf ${{ github.workspace }}/fotogalerie/*
            fi

      - name: Generate the gallery
        run: |
          docker run -t \
            -v ${{ github.workspace }}/css/gallery-custom.css:/custom.css:ro \
            -v ${{ github.workspace }}/fg-input:/input:ro \
            -v ${{ github.workspace }}/fotogalerie:/output \
            -u $(id -u):$(id -g) \
            ghcr.io/thumbsup/thumbsup:2.18.0 \
            thumbsup --input /input --output /output --title "VW Käferclub Lengenfeld" --locale "de" --theme cards --theme-style /custom.css --photo-quality "100" --video-quality "100" --home-album-name "Fotogalerie" --sort-albums-by "start-date" --sort-albums-direction "desc" --footer "Alle Bilder auf dieser Webseite unterliegen dem Urheberrecht von VW Käferclub Lengenfeld."

      - name: Commit and push updated gallery
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -f fotogalerie
          git commit -m "Update gallery [skip ci]" || echo "No changes to commit"
          git push origin master

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

        