name: Generate gallery and deploy site

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allows manual runs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create directory
        run: mkdir -p ${{ github.workspace }}/fotogalerie

      - name: Clear old files safely
        run: |
            if [ -d "${{ github.workspace }}/fotogalerie" ]; then
                rm -rf ${{ github.workspace }}/fotogalerie/*
            fi

      - name: Generate the gallery
        run: |
          docker run -t \
            -v ${{ github.workspace }}/css/gallery-custom.css:/custom.css:ro \
            -v ${{ github.workspace }}/fg-input:/input:ro \
            -v ${{ github.workspace }}/fotogalerie:/output \
            -u $(id -u):$(id -g) \
            ghcr.io/thumbsup/thumbsup:2.18.0 \
            thumbsup --input /input --output /output --title "VW Käferclub Lengenfeld" --locale "de" --theme cards --theme-style /custom.css --photo-quality "100" --video-quality "100" --home-album-name "Fotogalerie" --sort-albums-by "start-date" --sort-albums-direction "desc" --footer "Alle Bilder auf dieser Webseite unterliegen dem Urheberrecht von VW Käferclub Lengenfeld."

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: .
          clean: true